disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - todo
 - trailing_semicolon
 - sorted_imports
 - control_statement
 - trailing_newline
 - vertical_whitespace
 - empty_count
 - force_cast
 - force_try
 
excluded:
  - Frameworks
  - Pods
  - Submodule
  - Carthage
  - SME/TwitterPro
  - SME/Scenes/Schedules/ViewControllers/ChildScheduleControllers
  - SME/Helpers/Constants/KeyConstants.swift
  - SME/Scenes/Schedules/ViewControllers/ScheduleViewController.swift
  
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - force_unwrapping
  - legacy_constant

  - vertical_parameter_alignment_on_call
  - multiline_parameters
  - notification_center_detachment


file_name:
  excluded:
    - main.swift
    - AppDelegate.swift
    - SceneDelegate.swift
    
force_cast: warning
force_try: error
force_unwrapping: warning
legacy_constant: error
vertical_parameter_alignment_on_call: error
multiline_parameters: error
notification_center_detachment: error

warning_threshold: 110

line_length:
  error: 180
  ignores_comments: true
  
# they can set both implicitly with an array
type_body_length:
  - 400 # warning
  - 600 # error
# or they can set both explicitly


file_length:
  warning: 1200
  error: 1600

number_separator:
  minimum_length: 5

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded:
  - iPhone # excluded via string
  - Tag
  - Sme
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - i
    - id
    - URL
    - vc
    - stb
    - hud
    - HUD
    - Aya
    - db
    - to
    - qr
    - cr
    - y
    - t

